### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by shreyasminocha** [fpindia/OLD.fpindia.github.io#14]
I made some quick edits to the Haskell logo:

![Haskell logo with the colours of the Indian flag](https://user-images.githubusercontent.com/11537232/175854252-cdaf8465-dcd2-40b6-bb11-0f5bd557896c.svg)
.

**Comment by ajnsit** [comment]
Thanks for the suggestion, very creative!

The current logo is used in many places right now and changing it is going to be a bit of a pain. It would also feel like bikeshedding given the small size of the community right now. As the community grows, we will probably have to take another look at the logo at some point though and can consider changing the logo then.
